/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : localhost
Source Server Version : 120200
Source Host           : localhost:1521
Source Schema         : C##WSL

Target Server Type    : ORACLE
Target Server Version : 120200
File Encoding         : 65001

Date: 2019-06-21 09:29:23
*/


-- ----------------------------
-- Table structure for ADMINISTRATOR
-- ----------------------------
DROP TABLE "C##WSL"."ADMINISTRATOR";
CREATE TABLE "C##WSL"."ADMINISTRATOR" (
"AID" NUMBER NOT NULL ,
"ANUMBER" NUMBER NOT NULL ,
"APASSWORD" VARCHAR2(40 BYTE) NOT NULL ,
"ANAME" VARCHAR2(40 BYTE) NOT NULL ,
"ASEX" VARCHAR2(10 BYTE) NOT NULL ,
"ADEPARTMENT" VARCHAR2(40 BYTE) NOT NULL ,
"AEMAIL" VARCHAR2(40 BYTE) NULL ,
"APHONE" VARCHAR2(12 BYTE) NULL ,
"ALASTDATE" DATE NULL ,
"ALASTIP" CLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of ADMINISTRATOR
-- ----------------------------
INSERT INTO "C##WSL"."ADMINISTRATOR" VALUES ('1', '1', '1', '管理员', 'admin', 'aadmin', 'admin@admin.com', 'admin', TO_DATE('2019-06-05 16:54:48', 'YYYY-MM-DD HH24:MI:SS'), '0:0:0:0:0:0:0:1');

-- ----------------------------
-- Table structure for DEAPRTMENTLIST
-- ----------------------------
DROP TABLE "C##WSL"."DEAPRTMENTLIST";
CREATE TABLE "C##WSL"."DEAPRTMENTLIST" (
"DID" NUMBER NOT NULL ,
"DNAME" VARCHAR2(40 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of DEAPRTMENTLIST
-- ----------------------------
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('1', '文学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('2', '历史学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('3', '哲学与公共管理学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('4', '经济学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('5', '商学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('6', '国际关系学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('7', '法学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('8', '外国语学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('9', '数学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('10', '物理学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('11', '信息学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('12', '化学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('13', '生命科学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('14', '环境学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('15', '公共基础学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('16', '马克思主义学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('17', '体育教研部');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('18', '人口所');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('19', '计算中心');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('20', '广播影视学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('21', '留学生院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('22', '艺术学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('23', '新华国际商学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('24', '亚澳商学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('25', '轻型产业学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('26', '药学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('27', '汉语国际教育学院');
INSERT INTO "C##WSL"."DEAPRTMENTLIST" VALUES ('28', '新闻传播学院');

-- ----------------------------
-- Table structure for EXPAPPLICATION
-- ----------------------------
DROP TABLE "C##WSL"."EXPAPPLICATION";
CREATE TABLE "C##WSL"."EXPAPPLICATION" (
"SID" NUMBER NOT NULL ,
"CID" NUMBER NOT NULL ,
"EATIME" DATE NOT NULL ,
"EASTATE" NUMBER NOT NULL ,
"EARESULT" NUMBER DEFAULT -1  NULL ,
"LEADERSHIP" NUMBER DEFAULT NULL  NULL ,
"TEAMWORK" NUMBER DEFAULT NULL  NULL ,
"APPREHENSION" NUMBER DEFAULT NULL  NULL ,
"PRACTICE" NUMBER DEFAULT NULL  NULL ,
"ANALYSIS" NUMBER DEFAULT NULL  NULL ,
"INNOVATION" NUMBER DEFAULT NULL  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of EXPAPPLICATION
-- ----------------------------

-- ----------------------------
-- Table structure for EXPCOURSE
-- ----------------------------
DROP TABLE "C##WSL"."EXPCOURSE";
CREATE TABLE "C##WSL"."EXPCOURSE" (
"CID" NUMBER NOT NULL ,
"TITLE" VARCHAR2(100 BYTE) NULL ,
"CONTENT" CLOB NULL ,
"EXPTIME" DATE NOT NULL ,
"EXPSTATUS" NUMBER NOT NULL ,
"PUBLICTIME" DATE NULL ,
"TID" NUMBER NOT NULL ,
"ERID" NUMBER NULL ,
"AID" NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of EXPCOURSE
-- ----------------------------
INSERT INTO "C##WSL"."EXPCOURSE" VALUES ('13', '1', '11', TO_DATE('2019-04-29 14:24:52', 'YYYY-MM-DD HH24:MI:SS'), '0', null, '2', '1', null);

-- ----------------------------
-- Table structure for EXPEQUIPMENT
-- ----------------------------
DROP TABLE "C##WSL"."EXPEQUIPMENT";
CREATE TABLE "C##WSL"."EXPEQUIPMENT" (
"EQID" NUMBER NOT NULL ,
"EQNAME" VARCHAR2(40 BYTE) NOT NULL ,
"EQSTATE" VARCHAR2(20 BYTE) NOT NULL ,
"ERID" NUMBER NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of EXPEQUIPMENT
-- ----------------------------
INSERT INTO "C##WSL"."EXPEQUIPMENT" VALUES ('10001', '电脑', '1', '1');

-- ----------------------------
-- Table structure for EXPROOM
-- ----------------------------
DROP TABLE "C##WSL"."EXPROOM";
CREATE TABLE "C##WSL"."EXPROOM" (
"ERID" NUMBER NOT NULL ,
"ERADDRESS" VARCHAR2(50 BYTE) NOT NULL ,
"ERTELNUM" VARCHAR2(30 BYTE) NULL ,
"ERSTATE" NUMBER NOT NULL ,
"SUPERORDINATE" VARCHAR2(25 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of EXPROOM
-- ----------------------------
INSERT INTO "C##WSL"."EXPROOM" VALUES ('1', '哲理楼315', '024-2380574', '1', '信息学院');
INSERT INTO "C##WSL"."EXPROOM" VALUES ('2', '哲理楼202', '024-62203325', '1', '信息学院');

-- ----------------------------
-- Table structure for NOTIFICATION
-- ----------------------------
DROP TABLE "C##WSL"."NOTIFICATION";
CREATE TABLE "C##WSL"."NOTIFICATION" (
"NID" NUMBER NOT NULL ,
"TITLE" VARCHAR2(200 BYTE) NOT NULL ,
"CONTENT" CLOB NULL ,
"PUBLICTIME" DATE NOT NULL ,
"PUBLISHER" VARCHAR2(40 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of NOTIFICATION
-- ----------------------------
INSERT INTO "C##WSL"."NOTIFICATION" VALUES ('1', '岚湘老师嵌入式系统实验课暂停一次', '岚湘老师嵌入式系统实验课暂停一次，缺失课程下周四补上，特此通知', TO_DATE('2018-09-08 13:00:59', 'YYYY-MM-DD HH24:MI:SS'), '管理员');
INSERT INTO "C##WSL"."NOTIFICATION" VALUES ('2', '王晓恩老师计算机网络实验课暂停一次', '王晓恩老师计算机网络实验课暂停一次，缺失课程下周三补上，特此通知', TO_DATE('2018-09-08 13:30:59', 'YYYY-MM-DD HH24:MI:SS'), '管理员');
INSERT INTO "C##WSL"."NOTIFICATION" VALUES ('3', '陈安琪老师药物科学实验课暂停一次', '陈安琪老师药物科学实验课暂停一次，缺失课程下周四补上，特此通知', TO_DATE('2018-09-08 15:30:59', 'YYYY-MM-DD HH24:MI:SS'), '管理员');

-- ----------------------------
-- Table structure for STUDENT
-- ----------------------------
DROP TABLE "C##WSL"."STUDENT";
CREATE TABLE "C##WSL"."STUDENT" (
"SID" NUMBER NOT NULL ,
"SNUMBER" VARCHAR2(25 BYTE) NOT NULL ,
"SPASSWORD" VARCHAR2(50 BYTE) NOT NULL ,
"SNAME" VARCHAR2(50 BYTE) NOT NULL ,
"SSEX" VARCHAR2(20 BYTE) NOT NULL ,
"SDEPARTMENT" VARCHAR2(40 BYTE) NOT NULL ,
"SCLASS" VARCHAR2(40 BYTE) NOT NULL ,
"SGRADE" VARCHAR2(20 BYTE) NOT NULL ,
"LEADERSHIP" NUMBER DEFAULT 0  NULL ,
"TEAMWORK" NUMBER DEFAULT 0  NULL ,
"APPREHENSION" NUMBER DEFAULT 0  NULL ,
"PRACTICE" NUMBER DEFAULT 0  NULL ,
"ANALYSIS" NUMBER DEFAULT 0  NULL ,
"INNOVATION" NUMBER DEFAULT 0  NULL ,
"STELNUM" VARCHAR2(20 BYTE) NULL ,
"SLASTDATE" DATE NULL ,
"SLASTIP" CLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of STUDENT
-- ----------------------------
INSERT INTO "C##WSL"."STUDENT" VALUES ('1', '1', '1', '吴松林', '男', '信息学院', '计算机系统结构', '17', '90', '80', '90', '60', '70', '60', '13555715986', TO_DATE('2019-04-29 14:06:17', 'YYYY-MM-DD HH24:MI:SS'), '0:0:0:0:0:0:0:1');
INSERT INTO "C##WSL"."STUDENT" VALUES ('5', '141403107', '141403107', '王长海', '男', '信息学院', '计算机科学与技术1班', '14', '90', '85', '95', '93', '82', '69', '18640062728', TO_DATE('2018-09-13 07:32:26', 'YYYY-MM-DD HH24:MI:SS'), 'fd15:4ba5:5a2b:1008:fd32:1fd6:8e5a:24d5');
INSERT INTO "C##WSL"."STUDENT" VALUES ('3', '141403113', '141403113', '李佳乐', '男', '信息学院', '计算机科学与技术1班', '14', '89', '77', '93', '83', '81', '84', '15998236860', null, null);
INSERT INTO "C##WSL"."STUDENT" VALUES ('4', '141403112', '141403112', '张校铭', '男', '信息学院', '计算机科学与技术1班', '14', '75', '86', '81', '86', '85', '91', '15566032660', null, null);

-- ----------------------------
-- Table structure for TEACHER
-- ----------------------------
DROP TABLE "C##WSL"."TEACHER";
CREATE TABLE "C##WSL"."TEACHER" (
"TID" NUMBER NOT NULL ,
"TNUMBER" NUMBER NOT NULL ,
"TPASSWORD" VARCHAR2(40 BYTE) NOT NULL ,
"TNAME" VARCHAR2(40 BYTE) NOT NULL ,
"TSEX" VARCHAR2(10 BYTE) NOT NULL ,
"TPHONENUMBER" VARCHAR2(12 BYTE) NULL ,
"TDEPARTMENT" VARCHAR2(40 BYTE) NOT NULL ,
"TLASTDATE" DATE NULL ,
"TLASTIP" CLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of TEACHER
-- ----------------------------
INSERT INTO "C##WSL"."TEACHER" VALUES ('1', '1', '1', '宣伟宏', '1', '1', '信息学院', TO_DATE('2019-04-12 15:27:39', 'YYYY-MM-DD HH24:MI:SS'), '0:0:0:0:0:0:0:1');
INSERT INTO "C##WSL"."TEACHER" VALUES ('2', '6666', '6666', '曲大鹏', '男', '13704052945', '信息学院', TO_DATE('2019-04-29 14:07:16', 'YYYY-MM-DD HH24:MI:SS'), '0:0:0:0:0:0:0:1');
INSERT INTO "C##WSL"."TEACHER" VALUES ('11', '88', '88', '88', '男', '88', '信息学院', null, null);

-- ----------------------------
-- Sequence structure for S_S_LABSYS
-- ----------------------------
DROP SEQUENCE "C##WSL"."S_S_LABSYS";
CREATE SEQUENCE "C##WSL"."S_S_LABSYS"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 15
 NOCACHE ;

-- ----------------------------
-- Indexes structure for table ADMINISTRATOR
-- ----------------------------

-- ----------------------------
-- Checks structure for table ADMINISTRATOR
-- ----------------------------
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("AID" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ANUMBER" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("APASSWORD" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ANAME" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ASEX" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ADEPARTMENT" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("AID" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ANUMBER" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("APASSWORD" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ANAME" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ASEX" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ADEPARTMENT" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("AID" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ANUMBER" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("APASSWORD" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ANAME" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ASEX" IS NOT NULL);
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD CHECK ("ADEPARTMENT" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ADMINISTRATOR
-- ----------------------------
ALTER TABLE "C##WSL"."ADMINISTRATOR" ADD PRIMARY KEY ("AID");

-- ----------------------------
-- Indexes structure for table DEAPRTMENTLIST
-- ----------------------------

-- ----------------------------
-- Checks structure for table DEAPRTMENTLIST
-- ----------------------------
ALTER TABLE "C##WSL"."DEAPRTMENTLIST" ADD CHECK ("DID" IS NOT NULL);
ALTER TABLE "C##WSL"."DEAPRTMENTLIST" ADD CHECK ("DNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."DEAPRTMENTLIST" ADD CHECK ("DID" IS NOT NULL);
ALTER TABLE "C##WSL"."DEAPRTMENTLIST" ADD CHECK ("DNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."DEAPRTMENTLIST" ADD CHECK ("DID" IS NOT NULL);
ALTER TABLE "C##WSL"."DEAPRTMENTLIST" ADD CHECK ("DNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table DEAPRTMENTLIST
-- ----------------------------
ALTER TABLE "C##WSL"."DEAPRTMENTLIST" ADD PRIMARY KEY ("DID");

-- ----------------------------
-- Checks structure for table EXPAPPLICATION
-- ----------------------------
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("SID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("CID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("EATIME" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("EASTATE" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("SID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("CID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("EATIME" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("EASTATE" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("SID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("CID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("EATIME" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD CHECK ("EASTATE" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table EXPCOURSE
-- ----------------------------

-- ----------------------------
-- Triggers structure for table EXPCOURSE
-- ----------------------------
CREATE OR REPLACE TRIGGER "C##WSL"."TRI_INCREASE_ID" BEFORE INSERT ON "C##WSL"."EXPCOURSE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
declare
  nextid number;
begin
  IF :new.CID IS NULL or :new.CID=0 THEN --CID是列名
    select S_S_LABSYS.nextval --S_S_LABSYS正是刚才创建的序列
    into nextid
    from sys.dual;
    :new.CID:=nextid;
  end if;
end;
-- ----------------------------
-- Checks structure for table EXPCOURSE
-- ----------------------------
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("CID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("EXPTIME" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("EXPSTATUS" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("TID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("CID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("EXPTIME" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("EXPSTATUS" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("TID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("CID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("EXPTIME" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("EXPSTATUS" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPCOURSE" ADD CHECK ("TID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table EXPCOURSE
-- ----------------------------
ALTER TABLE "C##WSL"."EXPCOURSE" ADD PRIMARY KEY ("CID");

-- ----------------------------
-- Checks structure for table EXPEQUIPMENT
-- ----------------------------
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("EQID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("EQNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("EQSTATE" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("ERID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("EQID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("EQNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("EQSTATE" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("ERID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("EQID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("EQNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("EQSTATE" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD CHECK ("ERID" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table EXPROOM
-- ----------------------------

-- ----------------------------
-- Checks structure for table EXPROOM
-- ----------------------------
ALTER TABLE "C##WSL"."EXPROOM" ADD CHECK ("ERID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPROOM" ADD CHECK ("ERADDRESS" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPROOM" ADD CHECK ("ERSTATE" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPROOM" ADD CHECK ("ERID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPROOM" ADD CHECK ("ERADDRESS" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPROOM" ADD CHECK ("ERSTATE" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPROOM" ADD CHECK ("ERID" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPROOM" ADD CHECK ("ERADDRESS" IS NOT NULL);
ALTER TABLE "C##WSL"."EXPROOM" ADD CHECK ("ERSTATE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table EXPROOM
-- ----------------------------
ALTER TABLE "C##WSL"."EXPROOM" ADD PRIMARY KEY ("ERID");

-- ----------------------------
-- Indexes structure for table NOTIFICATION
-- ----------------------------

-- ----------------------------
-- Checks structure for table NOTIFICATION
-- ----------------------------
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("NID" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("TITLE" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("PUBLICTIME" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("PUBLISHER" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("NID" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("TITLE" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("PUBLICTIME" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("PUBLISHER" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("NID" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("TITLE" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("PUBLICTIME" IS NOT NULL);
ALTER TABLE "C##WSL"."NOTIFICATION" ADD CHECK ("PUBLISHER" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table NOTIFICATION
-- ----------------------------
ALTER TABLE "C##WSL"."NOTIFICATION" ADD PRIMARY KEY ("NID");

-- ----------------------------
-- Indexes structure for table STUDENT
-- ----------------------------

-- ----------------------------
-- Checks structure for table STUDENT
-- ----------------------------
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SID" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SNUMBER" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SPASSWORD" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SSEX" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SDEPARTMENT" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SCLASS" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SGRADE" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SID" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SNUMBER" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SPASSWORD" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SSEX" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SDEPARTMENT" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SCLASS" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SGRADE" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SID" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SNUMBER" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SPASSWORD" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SSEX" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SDEPARTMENT" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SCLASS" IS NOT NULL);
ALTER TABLE "C##WSL"."STUDENT" ADD CHECK ("SGRADE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table STUDENT
-- ----------------------------
ALTER TABLE "C##WSL"."STUDENT" ADD PRIMARY KEY ("SID");

-- ----------------------------
-- Indexes structure for table TEACHER
-- ----------------------------

-- ----------------------------
-- Checks structure for table TEACHER
-- ----------------------------
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TID" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TNUMBER" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TPASSWORD" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TSEX" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TDEPARTMENT" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TID" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TNUMBER" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TPASSWORD" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TSEX" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TDEPARTMENT" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TID" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TNUMBER" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TPASSWORD" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TNAME" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TSEX" IS NOT NULL);
ALTER TABLE "C##WSL"."TEACHER" ADD CHECK ("TDEPARTMENT" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TEACHER
-- ----------------------------
ALTER TABLE "C##WSL"."TEACHER" ADD PRIMARY KEY ("TID");

-- ----------------------------
-- Foreign Key structure for table "C##WSL"."EXPAPPLICATION"
-- ----------------------------
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD FOREIGN KEY ("SID") REFERENCES "C##WSL"."STUDENT" ("SID");
ALTER TABLE "C##WSL"."EXPAPPLICATION" ADD FOREIGN KEY ("CID") REFERENCES "C##WSL"."EXPCOURSE" ("CID");

-- ----------------------------
-- Foreign Key structure for table "C##WSL"."EXPCOURSE"
-- ----------------------------
ALTER TABLE "C##WSL"."EXPCOURSE" ADD FOREIGN KEY ("AID") REFERENCES "C##WSL"."ADMINISTRATOR" ("AID");
ALTER TABLE "C##WSL"."EXPCOURSE" ADD FOREIGN KEY ("TID") REFERENCES "C##WSL"."TEACHER" ("TID");
ALTER TABLE "C##WSL"."EXPCOURSE" ADD FOREIGN KEY ("ERID") REFERENCES "C##WSL"."EXPROOM" ("ERID");

-- ----------------------------
-- Foreign Key structure for table "C##WSL"."EXPEQUIPMENT"
-- ----------------------------
ALTER TABLE "C##WSL"."EXPEQUIPMENT" ADD FOREIGN KEY ("ERID") REFERENCES "C##WSL"."EXPROOM" ("ERID");
